spring:
  datasource:
    url: jdbc:mysql://192.168.123.125:3306/blogv2?characterEncoding=utf8&useSSL=true
    username: blogv2
    password: blogv2
    name: blogv2
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-wait-millis: 200
      max-total: 5
  application:
    name: BLOGV2

# mybatis配置
mybatis:
  config-location: classpath:mybatis.xml  # mybatis配置文件路径
  type-aliases-package: dev.hercat.com.blog.model  # 搜索参数类型路径
  mapper-locations:
    - classpath:mapper/*.xml

# 服务端口
server:
  port: 9092

# 配置日志
logging:
  level:
    root: info
